### ISSUE TITLE
Breaking change upgrading from 2.2.5 to 2.2.6 

### ISSUE THREAD

**Issue by artemverbo** [mitydigital/statamic-feedamic#16]
### Bug description

Hi @martyf ! Was good to meet you at the Aus/NZ meetup, I did not realise that we have one of the packages developed by you in one of our sites currently in development! Nice one!

Just noticed that our RSS feed route stopped working since upgrading to 2.2.6 (works well when downgraded to 2.2.5), it oddly is not working for one of the collections only, here is the problem: https://d.pr/i/JCFQOC Double checked that it does have dates enabled, it does have "tree structure" enabled though (`limit` is null in our feedamic config`):

```
title: 'Case Studies'
template: default
layout: layout
mount: e9d87dcc-1757-40f7-b4e3-be129b5fae06
revisions: false
route: '{{ mount }}/{{ sector | entrySlugFromId }}/{{ slug }}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  max_depth: 1
```

Did a quick investigation and can't find the problem from the first glance... Could it give you a hint what might be wrong? Thank you!

### Steps to reproduce

Upgrade from 2.2.5 to 2.2.6, error appears in /feed route.

### Environment and versions

```yaml
Environment
Laravel Version: 9.52.15
PHP Version: 8.1.22
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: ses
Queue: sync
Session: file

Statamic
Addons: 13
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.19.0 PRO

Statamic Addons
edalzell/forma: 2.1
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.1.3
mitydigital/feedamic: 2.2.6
pecotamic/sitemap: 1.4.6
rias/statamic-redirect: 3.1.0
statamic-rad-pack/mailchimp: 4.1.1
stillat/relationships: 2.1.1
```
