### ISSUE TITLE
Error on collections without a Date field

### ISSUE THREAD

**Issue by steveparks** [mitydigital/statamic-feedamic#29]
### Bug description

I'm successfully using Feedamic to create multiple feeds of different collections on my Statamic 5.x site. (thanks!)

But I've just hit a problem with creating a feed of a structured collection that doesn't have a Date field.

When navigating to this feed I get an error 'Object of class Illuminate\Support\Carbon could not be converted to int'.

On investigation, I think it's the lack of a Date field that is causing the problem.

In the Feedamic controller it requires a date field to sort the entries rather than sorting by the system ```updated_at``` metadata.

This may well be by design rather than a bug.

But perhaps there could be some minor docs improvements to mitigate this?

1. In the docs at https://docs.mity.com.au/feedamic/configuration/feeds at the end of the 'Collections' section, could be added "IMPORTANT: This means all collections to be included in feeds must be configured with Publish Dates enabled."

2. In the comments in feedamic.php could add as line 49: "Each collection must be configured with Publish Dates enabled."

Long term, maybe it'd be desirable to sort by ```updated_at``` instead when a date field isn't found?

### Steps to reproduce

1. Install Statamic 5.x, and Feedamic
2. Create a collection, don't add a Date field
3. Create a feed, specifying this collection.
4. Navigate to the feed in a browser

### Environment and versions

```yaml
Environment
Application Name: Convivio
Laravel Version: 11.20.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: convivio.test
Maintenance Mode: OFF
Timezone: Europe/London
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.4

Statamic
Addons: 11
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.19.0 PRO

Statamic Addons
goldnead/statamic-toc: 1.5
jonassiewertsen/statamic-livewire: 3.6.0
mitydigital/feedamic: 2.4.1
statamic/wikilinks: 2.1.0
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.2
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 6.3.1
tv2regionerne/statamic-passport: 1.4.1
tv2regionerne/statamic-private-api: 1.15.0
```

### Additional details

Thanks for a great addon!
